id: PE8EC7886
initial_creation_type: input
source_metadata:
  title: Rigdzin Nyima Drakpa
  language: nl
  description: 'Texts by and about the treasure-revealer Rigdzin Nyima Drakpa (rig
    ''dzin nyi ma grags pa, 1647–1710), alias Garwang Drodül Lingpa:'
  volume:
    12faa966cc554146a9023806ac5146c5:
      title: 'Marmé Mönlam: The Light Offering Prayer'
      parent: Aspiration Prayers
created_at: '2022-03-01T01:22:35.009538'
last_modified_at: '2022-03-01T01:22:35.009540'
